/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    QR: typeof import('./src/components/QR/index.jsx')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSelect: typeof import('@/components/theme-select')['default']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarOption: typeof import('@varlet/ui')['_OptionComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
  }
}
