/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Captcha: typeof import('./components/captcha/index.tsx')['default']
    QR: typeof import('./components/QR/index.tsx')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarChip: typeof import('@varlet/ui')['_ChipComponent']
    VarImage: typeof import('@varlet/ui')['_ImageComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
  }
  export interface ComponentCustomProperties {
    vRipple: typeof import('@varlet/ui')['_RippleComponent']
  }
}
